### ISSUE TITLE
4.1.1 code

### ISSUE THREAD

**Issue by Indyfish** [rubrik-devops/powershell-scripts#17]
We upgraded our code to 4.1.1 last we and since then this script is currently producing the following error.  

Connect-Rubrik : Cannot bind argument to parameter 'RubrikAddress' because it is an empty string.
At U:\scripts\manualsqlbackup.ps1:134 char:31
+ Connect-Rubrik -RubrikAddress $RubrikServer -RubrikCredential $Rubrik ...
+                               ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Connect-Rubrik], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Connect-Rubrik

Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a send.
At U:\scripts\manualsqlbackup.ps1:104 char:23
+ ...   $result = Invoke-WebRequest -Uri $uri -Headers $global:RubrikRESTHe ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by Indyfish** [comment]
added this line to my script and it worked normally.

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

**Comment by MikeFal** [comment]
Please update to the most recent version of the [Rubrik PowerShell module ](https://github.com/rubrikinc/PowerShell-Module). We added a TLS 1.2 fix (more or less the addition you are using) to the module several versions ago.
